import { FloodUpdate, District, AlertNotification } from './types';

export const mockUpdates: FloodUpdate[] = [
  {
    id: '1',
    time: '08:30 AM',
    location: 'Dibrugarh Town',
    district: 'Dibrugarh',
    waterLevel: 'critical',
    action: 'evacuate',
    details: 'Water level has crossed danger mark. Immediate evacuation required for low-lying areas.',
    timestamp: new Date('2026-03-22T08:30:00'),
  },
  {
    id: '2',
    time: '08:15 AM',
    location: 'Jorhat Central',
    district: 'Jorhat',
    waterLevel: 'danger',
    action: 'stay-alert',
    details: 'Water level rising steadily. Residents advised to stay alert and prepare for possible evacuation.',
    timestamp: new Date('2026-03-22T08:15:00'),
  },
  {
    id: '3',
    time: '07:45 AM',
    location: 'Tezpur City',
    district: 'Sonitpur',
    waterLevel: 'rising',
    action: 'stay-alert',
    details: 'Water level rising but below danger mark. Continue monitoring.',
    timestamp: new Date('2026-03-22T07:45:00'),
  },
  {
    id: '4',
    time: '07:30 AM',
    location: 'Guwahati Metro',
    district: 'Kamrup Metropolitan',
    waterLevel: 'normal',
    action: 'safe',
    details: 'Water levels stable. No immediate threat.',
    timestamp: new Date('2026-03-22T07:30:00'),
  },
  {
    id: '5',
    time: '07:00 AM',
    location: 'Nagaon Town',
    district: 'Nagaon',
    waterLevel: 'danger',
    action: 'evacuate',
    details: 'Flash flood warning issued. Evacuation centers opened at local schools.',
    timestamp: new Date('2026-03-22T07:00:00'),
  },
  {
    id: '6',
    time: '06:30 AM',
    location: 'Silchar City',
    district: 'Cachar',
    waterLevel: 'rising',
    action: 'stay-alert',
    details: 'Barak river showing rising trend. Monitor official channels.',
    timestamp: new Date('2026-03-22T06:30:00'),
  },
];

export const districts: District[] = [
  { id: 'baksa', name: 'Baksa', status: 'normal', waterLevel: 12.5, lastUpdated: new Date() },
  { id: 'barpeta', name: 'Barpeta', status: 'rising', waterLevel: 18.2, lastUpdated: new Date() },
  { id: 'biswanath', name: 'Biswanath', status: 'normal', waterLevel: 10.1, lastUpdated: new Date() },
  { id: 'bongaigaon', name: 'Bongaigaon', status: 'normal', waterLevel: 11.8, lastUpdated: new Date() },
  { id: 'cachar', name: 'Cachar', status: 'rising', waterLevel: 16.4, lastUpdated: new Date() },
  { id: 'charaideo', name: 'Charaideo', status: 'normal', waterLevel: 9.5, lastUpdated: new Date() },
  { id: 'chirang', name: 'Chirang', status: 'normal', waterLevel: 13.2, lastUpdated: new Date() },
  { id: 'darrang', name: 'Darrang', status: 'rising', waterLevel: 17.8, lastUpdated: new Date() },
  { id: 'dhemaji', name: 'Dhemaji', status: 'danger', waterLevel: 22.1, lastUpdated: new Date() },
  { id: 'dhubri', name: 'Dhubri', status: 'rising', waterLevel: 15.6, lastUpdated: new Date() },
  { id: 'dibrugarh', name: 'Dibrugarh', status: 'critical', waterLevel: 28.4, lastUpdated: new Date() },
  { id: 'dima-hasao', name: 'Dima Hasao', status: 'normal', waterLevel: 8.9, lastUpdated: new Date() },
  { id: 'goalpara', name: 'Goalpara', status: 'rising', waterLevel: 16.1, lastUpdated: new Date() },
  { id: 'golaghat', name: 'Golaghat', status: 'normal', waterLevel: 12.3, lastUpdated: new Date() },
  { id: 'hailakandi', name: 'Hailakandi', status: 'normal', waterLevel: 11.2, lastUpdated: new Date() },
  { id: 'hojai', name: 'Hojai', status: 'normal', waterLevel: 10.8, lastUpdated: new Date() },
  { id: 'jorhat', name: 'Jorhat', status: 'danger', waterLevel: 24.6, lastUpdated: new Date() },
  { id: 'kamrup', name: 'Kamrup', status: 'normal', waterLevel: 13.5, lastUpdated: new Date() },
  { id: 'kamrup-metro', name: 'Kamrup Metropolitan', status: 'normal', waterLevel: 12.1, lastUpdated: new Date() },
  { id: 'karbi-anglong', name: 'Karbi Anglong', status: 'normal', waterLevel: 9.2, lastUpdated: new Date() },
  { id: 'karimganj', name: 'Karimganj', status: 'rising', waterLevel: 15.8, lastUpdated: new Date() },
  { id: 'kokrajhar', name: 'Kokrajhar', status: 'normal', waterLevel: 11.5, lastUpdated: new Date() },
  { id: 'lakhimpur', name: 'Lakhimpur', status: 'danger', waterLevel: 23.2, lastUpdated: new Date() },
  { id: 'majuli', name: 'Majuli', status: 'critical', waterLevel: 26.8, lastUpdated: new Date() },
  { id: 'morigaon', name: 'Morigaon', status: 'danger', waterLevel: 21.4, lastUpdated: new Date() },
  { id: 'nagaon', name: 'Nagaon', status: 'danger', waterLevel: 24.1, lastUpdated: new Date() },
  { id: 'nalbari', name: 'Nalbari', status: 'rising', waterLevel: 17.2, lastUpdated: new Date() },
  { id: 'sivasagar', name: 'Sivasagar', status: 'rising', waterLevel: 18.5, lastUpdated: new Date() },
  { id: 'sonitpur', name: 'Sonitpur', status: 'rising', waterLevel: 19.1, lastUpdated: new Date() },
  { id: 'south-salmara', name: 'South Salmara-Mankachar', status: 'normal', waterLevel: 12.8, lastUpdated: new Date() },
  { id: 'tinsukia', name: 'Tinsukia', status: 'danger', waterLevel: 22.7, lastUpdated: new Date() },
  { id: 'udalguri', name: 'Udalguri', status: 'normal', waterLevel: 11.9, lastUpdated: new Date() },
  { id: 'west-karbi', name: 'West Karbi Anglong', status: 'normal', waterLevel: 10.4, lastUpdated: new Date() },
];

export const activeAlerts: AlertNotification[] = [
  {
    id: 'alert-1',
    type: 'emergency',
    title: 'EMERGENCY: Dibrugarh Evacuation',
    message: 'Immediate evacuation ordered for Dibrugarh district low-lying areas. Move to designated relief camps.',
    timestamp: new Date('2026-03-22T08:00:00'),
    isActive: true,
  },
  {
    id: 'alert-2',
    type: 'warning',
    title: 'Flood Warning: Majuli Island',
    message: 'High alert issued for Majuli. Residents advised to relocate valuables to higher ground.',
    timestamp: new Date('2026-03-22T07:30:00'),
    isActive: true,
  },
];

export const stats = {
  affectedDistricts: 12,
  peopleEvacuated: 45230,
  reliefCamps: 156,
  lastUpdated: new Date('2026-03-22T08:30:00'),
};
